version: "3"

services:
  api:
    image: api_dashboard
    build: ./docker/nest/
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ./api/:/api
    networks:
      - backend

  client:
    image: client_dashboard
    build: ./docker/react/
    container_name: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/client
    networks:
      - backend
  
networks:
    backend: